import type { SiteConfig } from "../types/site";

const contactEmail = "zoltan.fulop21@gmail.com";
const contactPhone = "+36 20 500 1702";

export const siteConfig = {
  lang: "hu",
  seo: {
    title: "Landora | Személyre szabott landing page-ek",
    description:
      "Személyre szabott landing page-ek, bevált alapokra építve. Tartalom, felépítés és megjelenés a vállalkozásodhoz igazítva.",
    image: "/images/hero-workspace.png",
    imageAlt: "Letisztult munkakörnyezet landing page tervezéshez",
    type: "website",
    twitterCard: "summary_large_image",
  },
  brand: {
    name: "Landora",
    role: "Személyre szabott landing page-ek",
    initials: "L",
    logo: "/images/landora-logo.png",
    description:
      "Konfigurációvezérelt Astro landing page sablon személyre szabható tartalommal, szekciókkal és témával.",
  },
  theme: {
    colorScheme: "light",
    variables: {
      "--color-ink": "#17211d",
      "--color-muted": "#65736b",
      "--color-bg": "#f7f8f3",
      "--color-surface": "#ffffff",
      "--color-surface-strong": "#eef3ec",
      "--color-line": "#dce4da",
      "--color-accent": "#c75f48",
      "--color-accent-strong": "#9d3f2e",
      "--color-sage": "#7f997f",
      "--color-blue": "#416979",
      "--color-white": "#ffffff",
      "--color-text-soft": "#4f5f57",
      "--color-document-text": "#43534b",
      "--color-field-line": "#cfd9ce",
      "--color-primary-hover": "#26362f",
      "--color-header-border": "rgba(220, 228, 218, 0.82)",
      "--color-header-bg": "rgba(247, 248, 243, 0.88)",
      "--color-brand-mark-bg": "#f5f3ec",
      "--color-nav-hover-bg": "rgba(127, 153, 127, 0.13)",
      "--color-selection": "rgba(199, 95, 72, 0.22)",
      "--color-focus-ring": "rgba(199, 95, 72, 0.5)",
      "--color-button-secondary-border": "rgba(23, 33, 29, 0.18)",
      "--color-button-secondary-border-hover": "rgba(23, 33, 29, 0.36)",
      "--color-button-secondary-bg": "rgba(255, 255, 255, 0.72)",
      "--color-hero-bg": "#f4f5ef",
      "--color-hero-stat-line": "rgba(199, 95, 72, 0.42)",
      "--color-contact-link-line": "rgba(199, 95, 72, 0.4)",
      "--color-contact-field-focus": "rgba(199, 95, 72, 0.78)",
      "--shadow-contact-field-focus": "0 0 0 4px rgba(199, 95, 72, 0.12)",
      "--color-dark-section-eyebrow": "#f0ab90",
      "--color-dark-section-text": "rgba(255, 255, 255, 0.76)",
      "--color-dark-section-text-strong": "rgba(255, 255, 255, 0.82)",
      "--color-dark-section-text-muted": "rgba(255, 255, 255, 0.68)",
      "--color-dark-section-line": "rgba(255, 255, 255, 0.13)",
      "--color-dark-section-line-strong": "rgba(255, 255, 255, 0.18)",
      "--color-dark-section-surface": "rgba(255, 255, 255, 0.06)",
      "--color-dark-section-surface-strong": "rgba(23, 33, 29, 0.58)",
      "--color-legal-accent-bg": "rgba(127, 153, 127, 0.14)",
      "--color-cta-accent-bg": "rgba(127, 153, 127, 0.18)",
      "--shadow-soft": "0 22px 60px rgba(23, 33, 29, 0.1)",
      "--container": "1180px",
      "--radius": "8px",
    },
  },
  assets: {
    faviconSvg: "/favicon.svg",
    faviconIco: "/favicon.ico",
    preloadImages: ["/images/hero-workspace.png"],
  },
  header: {
    cta: {
      label: "Email",
      href: `mailto:${contactEmail}`,
      ariaLabel: "Email küldése",
    },
  },
  navigation: [
    { label: "Mit szabunk rád?", href: "#services" },
    { label: "Miért Landora?", href: "#trust" },
    { label: "Folyamat", href: "#about" },
    { label: "Kapcsolat", href: "#contact" },
  ],
  landing: {
    sections: [
      { id: "hero", enabled: true },
      { id: "services", enabled: true },
      { id: "aboutTrust", enabled: true },
      { id: "cta", enabled: true },
      { id: "contact", enabled: true },
    ],
  },
  hero: {
    eyebrow: "Landing page a te vállalkozásodra hangolva",
    title: "Személyre szabott landing page-ek, bevált alapokra építve.",
    lead: "Olyan landing page-et kapsz, amely a szolgáltatásaidhoz, célközönségedhez, arculatodhoz és üzleti célodhoz igazodik. Nem kész sablont töltünk fel szöveggel, hanem a te ajánlatod köré építjük fel az oldalt.",
    image: {
      src: "/images/hero-workspace.png",
      alt: "",
    },
    primaryAction: { label: "Beszéljük át az oldaladat", href: "#contact" },
    secondaryAction: { label: "Mit szabunk személyre?", href: "#services" },
    stats: [
      { value: "Saját üzenet", label: "a vállalkozásodhoz igazítva" },
      { value: "Saját felépítés", label: "a látogatóid döntéseire hangolva" },
      { value: "Saját cél", label: "kapcsolat, ajánlatkérés vagy bemutatkozás" },
    ],
  },
  servicesIntro: {
    eyebrow: "Személyre szabás",
    title: "Minden fontos részlet a vállalkozásodhoz igazodik.",
    lead: "A jó landing page nem attól működik, hogy sok elemet tartalmaz. Attól lesz érthető, hogy pontosan azt mondja, azt mutatja és arra vezeti a látogatót, amire a te vállalkozásodnak szüksége van.",
  },
  services: [
    {
      title: "Tartalom és fő üzenet",
      text: "Megfogalmazzuk, mit kínálsz, kinek segítesz, és miért érdemes téged választani. A szöveg természetes, tömör és a célközönséged nyelvén szól.",
    },
    {
      title: "Oldal felépítése",
      text: "A szekciók sorrendje és tartalma az ajánlatodhoz igazodik. A látogató így lépésről lépésre érti meg, mit kap és hogyan tud kapcsolatba lépni veled.",
    },
    {
      title: "Megjelenés és arculat",
      text: "A vizuális irány a vállalkozásod karakterét követi: lehet letisztult, elegáns, közvetlen vagy prémium hangulatú, de mindig következetes és hiteles.",
    },
    {
      title: "Kapcsolat, ahogy neked működik",
      text: "Nem mindenkinek ugyanaz a jó kapcsolatfelvételi út. Lehet egyszerű email, telefonos megkeresés vagy rövid űrlap; azt választjuk, ami a te ügyfeleidnek természetes.",
    },
  ],
  about: {
    eyebrow: "Folyamat",
    title: "Először megértjük, mit kell az oldalnak elérnie.",
    lead: "A közös munka nem egy látványos blokkal indul, hanem a vállalkozásod megértésével. Megnézzük, mit szeretnél bemutatni, kikhez beszélsz, milyen hang illik hozzád, és milyen célra kell vezetnie az oldalnak.",
    steps: [
      "Rövid egyeztetés a szolgáltatásaidról, célközönségedről és az oldal céljáról.",
      "Személyre szabott oldalstruktúra, fő üzenet és kapcsolati útvonal kialakítása.",
      "Letisztult landing page elkészítése a saját arculatodhoz és ajánlatodhoz igazítva.",
    ],
  },
  trust: {
    eyebrow: "Megjelenés és szerkezet",
    title: "Egyedi megjelenés, átgondolt szerkezet.",
    items: [
      {
        value: "A vállalkozásodhoz igazítva",
        label: "A megjelenés, a tartalom és a hangsúlyok mindig ahhoz igazodnak, amit képviselsz.",
      },
      {
        value: "Átgondolt felépítés",
        label: "A tartalom logikusan épül fel, hogy a látogató gyorsan megtalálja, amit keres, és könnyen kapcsolatba léphessen veled.",
      },
      {
        value: "Egységes összhatás",
        label: "A színek, a képek, a szöveg és a részletek együtt adják vissza a vállalkozásod karakterét.",
      },
    ],
  },
  cta: {
    eyebrow: "Következő lépés",
    title: "Nézzük meg, milyen landing page illik a vállalkozásodhoz.",
    text: "Írj röviden arról, mivel foglalkozol, kinek szól az ajánlatod, és mit szeretnél elérni az oldallal. Egy rövid egyeztetésen átbeszéljük a legjobb irányt.",
    primaryAction: { label: "Kérek egy rövid egyeztetést", href: "#contact" },
    secondaryAction: { label: "Vissza a személyre szabáshoz", href: "#services" },
  },
  contact: {
    eyebrow: "Kapcsolat",
    title: "Beszéljük át az oldaladat.",
    lead: "Nem kell kész brief. Elég, ha pár mondatban leírod, milyen vállalkozásnak készülne a landing page, és mi lenne az oldal fő célja.",
    email: contactEmail,
    phone: contactPhone,
    city: "Dunakiliti",
    form: {
      action: `mailto:${contactEmail}`,
      method: "post",
      enctype: "text/plain",
      submitLabel: "Üzenet küldése",
      fields: [
        {
          id: "name",
          name: "Név",
          label: "Név",
          autocomplete: "name",
          required: true,
        },
        {
          id: "email",
          name: "Email",
          label: "Email",
          type: "email",
          autocomplete: "email",
          required: true,
        },
        {
          id: "message",
          name: "Projekt",
          label: "Projekt röviden",
          type: "textarea",
          rows: 5,
          required: true,
        },
      ],
    },
  },
  legal: {
    title: "Impresszum",
    description: "A Landora weboldal szolgáltatói és kapcsolatfelvételi adatai.",
    lead: "Ezen az oldalon a Landora weboldal üzemeltetésével és a szolgáltatóval kapcsolatos alapadatok találhatók. A kiegészítendő mezőket az éles publikálás előtt pontosítani kell.",
    operatorName: "Kiegészítendő: szolgáltató neve / vállalkozó neve",
    brandName: "Landora",
    address: "Kiegészítendő: pontos székhely vagy lakcím, Dunakiliti",
    email: contactEmail,
    phone: contactPhone,
    taxNumber: "Kiegészítendő: adószám, ha releváns",
    registrationAuthority: "Kiegészítendő: nyilvántartó hatóság vagy bíróság, ha releváns",
    registrationNumber: "Kiegészítendő: nyilvántartási szám, ha releváns",
    hostingProvider: "Kiegészítendő: tárhelyszolgáltató neve",
    hostingProviderAddress: "Kiegészítendő: tárhelyszolgáltató székhelye / címe",
    hostingProviderEmail: "Kiegészítendő: tárhelyszolgáltató kapcsolattartási email címe",
    activity:
      "Személyre szabott landing page-ek tervezése és elkészítése vállalkozások számára.",
    updatedAt: "2026. augusztus 15.",
  },
  footer: {
    copyright: "Minden jog fenntartva.",
    links: [
      { label: "Mit szabunk rád?", href: "#services" },
      { label: "Miért Landora?", href: "#trust" },
      { label: "Kapcsolat", href: "#contact" },
      { label: "Impresszum", href: "/impresszum/" },
      { label: "Adatkezelés", href: "/adatkezeles/" },
    ],
  },
} satisfies SiteConfig;
